functional:
  - Пользователь может зарегестрироваться
  - Пользователь может авторизоваться по email
  - Пользователь может авторизоваться через соцсети
  - Пользователь может зайти в личный кабинет
  - Пользователь может выбрать уроворень сложности
  - Пользователь может выбрать соперника
  - Пользователь должен иметь возможность ввести код
  - Пользователь может выбрать язык программирования из списка
  - Пользователь может выбрать время тура
  - Пользователь может выбрать задачу из списка или рандомную
  - Пользователь может общатся с другими пользователями в чате
  - Пользователь может посмотреть турниры и завершённые игры
  - Пользователь может выйти из игры в любой момент
  - Пользователь может сбросить редактор
  - Пользователь может проверить решение
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
   - Сайт должен иметь мобильную версию
implicit:
  - Сайт должен иметь выбор языка
  - Нажатие на логотип - возвращает на главную (начальную) страницу
  - Отпрвление сообщений в чате должно быть по нажатию "Enter"/ кнопки "Send"
